### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by narghar** [LukaszBielsko/simple-twitter-bot#2]
The bot works great, but it would be fine to provide install instructions.
1. Clone or download
2. `npm install`
3. Create twitter account.
4. Apply for dev accout on twitter
5. Set up your application
6. Get your tokens 
7. Create file **twit-config.js** open it and add this code:
```
module.exports = {
  consumer_key: 'Please insert yours consumer_key',
  consumer_secret: 'Please insert yours consumer_secret',
  access_token: 'Please insert yours access_token',
  access_token_secret: 'Please insert yours access_token_secret',
  timeout_ms: 60 * 1000, // optional HTTP request timeout to apply to all requests.
  strictSSL: true, // optional - requires SSL certificates to be valid.
}
```
8. `npm start`
9. Wait for 3 hours and check your twitter dashboard :satisfied:

**Comment by LukaszBielsko** [comment]
done

thanks
